apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/plabs/go-k8s-healthcheck
  newTag: "1.0.0"

patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: go-k8s-healthcheck
