apiVersion: v1
kind: ConfigMap
metadata:
  name: go-k8s-healthcheck-config
  namespace: healthcheck
  labels:
    app.kubernetes.io/name: go-k8s-healthcheck
data:
  PORT: "8080"
  LOG_LEVEL: "info"
  SHUTDOWN_TIMEOUT_SEC: "30"
  APP_NAME: "go-k8s-healthcheck"
