apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-k8s-healthcheck
  namespace: healthcheck
  labels:
    app.kubernetes.io/name: go-k8s-healthcheck
    app.kubernetes.io/component: server
automountServiceAccountToken: false
