apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-healthcheck
spec:
  # Dev: single replica is fine, saves resources
  replicas: 1
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "64Mi"
