apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-healthcheck
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: server
        env:
        - name: APP_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "64Mi"
